/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "P2r"
 * 	found in "P2r.asn1"
 */

#ifndef	_Cause_H_
#define	_Cause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cause {
	Cause_undefined	= 0,
	Cause_success	= 1,
	Cause_timeout	= 2,
	Cause_error	= 3,
	Cause_no_resources	= 4
	/*
	 * Enumeration is extensible
	 */
} e_Cause;

/* Cause */
typedef long	 Cause_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Cause_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Cause;
extern const asn_INTEGER_specifics_t asn_SPC_Cause_specs_1;
asn_struct_free_f Cause_free;
asn_struct_print_f Cause_print;
asn_constr_check_f Cause_constraint;
ber_type_decoder_f Cause_decode_ber;
der_type_encoder_f Cause_encode_der;
xer_type_decoder_f Cause_decode_xer;
xer_type_encoder_f Cause_encode_xer;
oer_type_decoder_f Cause_decode_oer;
oer_type_encoder_f Cause_encode_oer;
per_type_decoder_f Cause_decode_uper;
per_type_encoder_f Cause_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cause_H_ */
#include <asn_internal.h>
