/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "P2r"
 * 	found in "P2r.asn1"
 */

#include "MessageTypes.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_MessageTypes_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_MessageTypes_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_MessageTypes_value2enum_1[] = {
	{ 0,	4,	"none" },
	{ 1,	34,	"id-p2r-session-termination-warning" },
	{ 2,	38,	"id-p2r-session-termination-warning-ack" },
	{ 3,	41,	"id-p2r-session-termination-warning-cancel" },
	{ 4,	30,	"id-p2r-session-restore-warning" },
	{ 5,	31,	"id-p2r-speed-level-notification" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_MessageTypes_enum2value_1[] = {
	4,	/* id-p2r-session-restore-warning(4) */
	1,	/* id-p2r-session-termination-warning(1) */
	2,	/* id-p2r-session-termination-warning-ack(2) */
	3,	/* id-p2r-session-termination-warning-cancel(3) */
	5,	/* id-p2r-speed-level-notification(5) */
	0	/* none(0) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_MessageTypes_specs_1 = {
	asn_MAP_MessageTypes_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_MessageTypes_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_MessageTypes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_MessageTypes = {
	"MessageTypes",
	"MessageTypes",
	&asn_OP_NativeEnumerated,
	asn_DEF_MessageTypes_tags_1,
	sizeof(asn_DEF_MessageTypes_tags_1)
		/sizeof(asn_DEF_MessageTypes_tags_1[0]), /* 1 */
	asn_DEF_MessageTypes_tags_1,	/* Same as above */
	sizeof(asn_DEF_MessageTypes_tags_1)
		/sizeof(asn_DEF_MessageTypes_tags_1[0]), /* 1 */
	{ &asn_OER_type_MessageTypes_constr_1, &asn_PER_type_MessageTypes_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_MessageTypes_specs_1	/* Additional specs */
};

