/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "P2r"
 * 	found in "P2r.asn1"
 */

#ifndef	_MessageTypes_H_
#define	_MessageTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MessageTypes {
	MessageTypes_none	= 0,
	MessageTypes_id_p2r_connection_setup_request	= 1,
	MessageTypes_id_p2r_connection_setup_response	= 2,
	MessageTypes_id_p2r_connection_release	= 3,
	MessageTypes_id_p2r_connection_release_ack	= 4,
	MessageTypes_id_p2r_session_termination_warning	= 5,
	MessageTypes_id_p2r_session_termination_warning_ack	= 6,
	MessageTypes_id_p2r_session_termination_warning_cancel	= 7,
	MessageTypes_id_p2r_session_restore_warning	= 8,
	MessageTypes_id_p2r_session_restore_warning_ack	= 9,
	MessageTypes_id_p2r_speed_level_notification	= 10
	/*
	 * Enumeration is extensible
	 */
} e_MessageTypes;

/* MessageTypes */
typedef long	 MessageTypes_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MessageTypes_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MessageTypes;
extern const asn_INTEGER_specifics_t asn_SPC_MessageTypes_specs_1;
asn_struct_free_f MessageTypes_free;
asn_struct_print_f MessageTypes_print;
asn_constr_check_f MessageTypes_constraint;
ber_type_decoder_f MessageTypes_decode_ber;
der_type_encoder_f MessageTypes_encode_der;
xer_type_decoder_f MessageTypes_decode_xer;
xer_type_encoder_f MessageTypes_encode_xer;
oer_type_decoder_f MessageTypes_decode_oer;
oer_type_encoder_f MessageTypes_encode_oer;
per_type_decoder_f MessageTypes_decode_uper;
per_type_encoder_f MessageTypes_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageTypes_H_ */
#include <asn_internal.h>
