/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "P2r"
 * 	found in "P2r.asn1"
 */

#include "P2RConnectionSetupResponse.h"

asn_TYPE_member_t asn_MBR_P2RConnectionSetupResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct P2RConnectionSetupResponse, cause),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cause"
		},
};
static const ber_tlv_tag_t asn_DEF_P2RConnectionSetupResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_P2RConnectionSetupResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* cause */
};
asn_SEQUENCE_specifics_t asn_SPC_P2RConnectionSetupResponse_specs_1 = {
	sizeof(struct P2RConnectionSetupResponse),
	offsetof(struct P2RConnectionSetupResponse, _asn_ctx),
	asn_MAP_P2RConnectionSetupResponse_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_P2RConnectionSetupResponse = {
	"P2RConnectionSetupResponse",
	"P2RConnectionSetupResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_P2RConnectionSetupResponse_tags_1,
	sizeof(asn_DEF_P2RConnectionSetupResponse_tags_1)
		/sizeof(asn_DEF_P2RConnectionSetupResponse_tags_1[0]), /* 1 */
	asn_DEF_P2RConnectionSetupResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_P2RConnectionSetupResponse_tags_1)
		/sizeof(asn_DEF_P2RConnectionSetupResponse_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_P2RConnectionSetupResponse_1,
	1,	/* Elements count */
	&asn_SPC_P2RConnectionSetupResponse_specs_1	/* Additional specs */
};

