/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "P2r"
 * 	found in "P2r.asn1"
 */

#ifndef	_Parameters_H_
#define	_Parameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "P2RConnectionSetupResponse.h"
#include "P2RConnectionRelease.h"
#include "P2RConnectionReleaseAck.h"
#include "P2RSessionTerminationWarning.h"
#include "P2RSessionTerminationWarningAck.h"
#include "P2RSessionTerminationWarningCancel.h"
#include "P2RSessionRestoreWarning.h"
#include "P2RSessionRestoreWarningAck.h"
#include "P2RSpeedLevelNotification.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Parameters_PR {
	Parameters_PR_NOTHING,	/* No components present */
	Parameters_PR_connection_setup_request,
	Parameters_PR_connection_setup_response,
	Parameters_PR_connection_release,
	Parameters_PR_connection_release_ack,
	Parameters_PR_session_termination_warning,
	Parameters_PR_session_termination_warning_ack,
	Parameters_PR_session_termination_warning_cancel,
	Parameters_PR_session_restore_warning,
	Parameters_PR_session_restore_warning_ack,
	Parameters_PR_speed_level_notification
	/* Extensions may appear below */
	
} Parameters_PR;

/* Parameters */
typedef struct Parameters {
	Parameters_PR present;
	union Parameters_u {
		NULL_t	 connection_setup_request;
		P2RConnectionSetupResponse_t	 connection_setup_response;
		P2RConnectionRelease_t	 connection_release;
		P2RConnectionReleaseAck_t	 connection_release_ack;
		P2RSessionTerminationWarning_t	 session_termination_warning;
		P2RSessionTerminationWarningAck_t	 session_termination_warning_ack;
		P2RSessionTerminationWarningCancel_t	 session_termination_warning_cancel;
		P2RSessionRestoreWarning_t	 session_restore_warning;
		P2RSessionRestoreWarningAck_t	 session_restore_warning_ack;
		P2RSpeedLevelNotification_t	 speed_level_notification;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Parameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Parameters;
extern asn_CHOICE_specifics_t asn_SPC_Parameters_specs_1;
extern asn_TYPE_member_t asn_MBR_Parameters_1[10];
extern asn_per_constraints_t asn_PER_type_Parameters_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Parameters_H_ */
#include <asn_internal.h>
