/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "P2r"
 * 	found in "P2r.asn1"
 */

#include "Parameters.h"

static asn_oer_constraints_t asn_OER_type_Parameters_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Parameters_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Parameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Parameters, choice.session_termination_warning),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_P2RSessionTerminationWarning,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"session-termination-warning"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Parameters, choice.session_termination_warning_ack),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_P2RSessionTerminationWarningAck,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"session-termination-warning-ack"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Parameters, choice.session_termination_warning_cancel),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_P2RSessionTerminationWarningCancel,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"session-termination-warning-cancel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Parameters, choice.session_restore_warning),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_P2RSessionRestoreWarning,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"session-restore-warning"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Parameters, choice.speed_level_notification),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_P2RSpeedLevelNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speed-level-notification"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Parameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* session-termination-warning */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* session-termination-warning-ack */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* session-termination-warning-cancel */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* session-restore-warning */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* speed-level-notification */
};
asn_CHOICE_specifics_t asn_SPC_Parameters_specs_1 = {
	sizeof(struct Parameters),
	offsetof(struct Parameters, _asn_ctx),
	offsetof(struct Parameters, present),
	sizeof(((struct Parameters *)0)->present),
	asn_MAP_Parameters_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Parameters = {
	"Parameters",
	"Parameters",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Parameters_constr_1, &asn_PER_type_Parameters_constr_1, CHOICE_constraint },
	asn_MBR_Parameters_1,
	5,	/* Elements count */
	&asn_SPC_Parameters_specs_1	/* Additional specs */
};

