/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "P2r"
 * 	found in "P2r.asn1"
 */

#ifndef	_ProtocolVersion_H_
#define	_ProtocolVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolVersion */
typedef struct ProtocolVersion {
	long	 major_version;
	long	 minor_version;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolVersion;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtocolVersion_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolVersion_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolVersion_H_ */
#include <asn_internal.h>
